version: '3'

services:
   mysq-server:
     image: mysql:5.7
     container_name: mysql-server
     hostname: mysql
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     volumes:
       - db_data:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
       - ./backup:/backup
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: zabbix
       MYSQL_DATABASE: zabbix
       MYSQL_USER: zabbix
       MYSQL_PASSWORD: zabbix
  
   zabbix-server:
      image: zabbix/zabbix-server-mysql:latest
      container_name: zabbix-server
      hostname: zabbix-server
      environment:
        DB_SERVER_HOST: mysq-server
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: zabbix
        MYSQL_ROOT_PASSWORD: zabbix
        ZBX_JAVAGATEWAY: gateway-java
        ZBX_DEBUGLEVEL: 2
        TZ: America/Fortaleza
        PHP_TZ: America/Fortaleza
      links:
        - mysq-server
      ports:
        - "10051:10051"
      volumes:
        - /etc/localtime:/etc/localtime:ro

   zabbix-web:
      image: zabbix/zabbix-web-nginx-mysql:latest
      container_name: zabbix-web
      hostname: zabbix-web
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_DATABASE: zabbix
        MYSQL_USER: zabbix
        MYSQL_PASSWORD: zabbix
        MYSQL_ROOT_PASSWORD: zabbix
        TZ: America/Fortaleza
        PHP_TZ: America/Fortaleza        
      links:
        - mysq-server
        - zabbix-server
      ports:
        - "80:80" 
volumes:
  db_data:
